# https://jupyter-docker-stacks.readthedocs.io/en/latest/
# https://hub.docker.com/r/bitnami/spark/
services:
  jupyter-pyspark-notebook:
    build: ./docker/jupyter-pyspark
    depends_on:
      - spark-master
    environment:
      NOTEBOOK_ARGS: --NotebookApp.token=''
    ports:
      - '8888:8888'
      - '4040-4060:4040-4060'
    volumes:
      - ./data:/opt/workspace
      - ./notebooks:/home/jovyan/work/notebooks
      - ./pyscripts:/home/jovyan/work/pyscripts
      - ./spark.conf:/opt/bitnami/spark/conf/spark-defaults.conf
  spark-master:
    image: docker.io/bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data:/opt/workspace
      - ./spark.conf:/opt/bitnami/spark/conf/spark-defaults.conf
  spark-worker:
    image: docker.io/bitnami/spark:3.5.0
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./data:/opt/workspace
      - ./spark.conf:/opt/bitnami/spark/conf/spark-defaults.conf
  kafka-producer:
    build: ./docker/kafka-producer
    depends_on:
      - kafka-broker
    environment:
      - KAFKA_HOST=kafka-broker:29092
      - KAFKA_TOPIC=web-events
      - SIMULATION_TIME_SECONDS=86400
      - USER_POOL_SIZE=100
      - SESSIONS_PER_DAY=100000
  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka-broker:
    image: docker.io/confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1